### ISSUE TITLE
Failed build on 2025.10

### ISSUE THREAD

**Issue by caideone** [v1ack/lelight-esphome#3]
In file included from src/esphome/components/ble_lelight/ble_lelight.cpp:1:
src/esphome/components/ble_lelight/ble_lelight.h:62:8: error: 'queue' in namespace 'std' does not name a template type
   62 |   std::queue<BleLeCommand> lamp_commands_queue;
      |        ^~~~~
src/esphome/components/ble_lelight/ble_lelight.h:14:1: note: 'std::queue' is defined in header '<queue>'; this is probably fixable by adding '#include <queue>'
   13 | #include "encoder.h"
  +++ |+#include <queue>
   14 | 
src/esphome/components/ble_lelight/ble_lelight.cpp: In member function 'virtual void esphome::ble_lelight::BleLeLight::loop()':
src/esphome/components/ble_lelight/ble_lelight.cpp:84:13: error: 'class esphome::ble_lelight::BleLeLight' has no member named 'lamp_commands_queue'
   84 |   if (this->lamp_commands_queue.empty()) {
      |             ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ble_lelight/ble_lelight.cpp:87:24: error: 'class esphome::ble_lelight::BleLeLight' has no member named 'lamp_commands_queue'
   87 |   auto command = this->lamp_commands_queue.front();
      |                        ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ble_lelight/ble_lelight.cpp:88:9: error: 'class esphome::ble_lelight::BleLeLight' has no member named 'lamp_commands_queue'
   88 |   this->lamp_commands_queue.pop();
      |         ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ble_lelight/ble_lelight.cpp: In member function 'virtual void esphome::ble_lelight::BleLeLight::write_state(esphome::light::LightState*)':
src/esphome/components/ble_lelight/ble_lelight.cpp:128:14: error: 'class esphome::ble_lelight::BleLeLight' has no member named 'lamp_commands_queue'
  128 |   if (!this->lamp_commands_queue.empty()) {
      |              ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ble_lelight/ble_lelight.cpp:136:9: error: 'class esphome::ble_lelight::BleLeLight' has no member named 'lamp_commands_queue'
  136 |   this->lamp_commands_queue.push(is_on ? BleLeCommands::turn_on() : BleLeCommands::turn_off());
      |         ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ble_lelight/ble_lelight.cpp:139:11: error: 'class esphome::ble_lelight::BleLeLight' has no member named 'lamp_commands_queue'
  139 |     this->lamp_commands_queue.push(BleLeCommands::temp(color_temperature));
      |           ^~~~~~~~~~~~~~~~~~~
src/esphome/components/ble_lelight/ble_lelight.cpp:140:11: error: 'class esphome::ble_lelight::BleLeLight' has no member named 'lamp_commands_queue'
  140 |     this->lamp_commands_queue.push(BleLeCommands::bright(brightness));
      |           ^~~~~~~~~~~~~~~~~~~
*** [.pioenvs/lamp/src/esphome/components/ble_lelight/ble_lelight.cpp.o] Error 1
========================= [FAILED] Took 92.58 seconds =========================

**Comment by v1ack** [comment]
Yes, was a bug, fixed
